feat: product-cart 페이지 마크업
FRONTENDSCHOOL10/Code12hour pull request #22
Opened 2024-07-10 15:46 UTC by devHyeon99

### 제목 : feat(11): product-cart 페이지 마크업

### PR 유형

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### 🔎 작업 내용
- 아코디언 details, summary 태그 사용하여 구현
- 전체선택시 상단, 하단 체크박스 동시 선택 가능하게 구현
- 기능적 요소 제외 마크업 및 스타일링 완료
<br />

### 🔧 앞으로의 과제
- 중간 빌드 및 배포 진행 해보기
- 로그인 페이지 헤더, 푸터 연결
<br />

### 이슈

resolves #11

2024-07-10 18:46 UTC, happyhye requested changes
검토했습니다! 리뷰 참고 바랍니다!

2024-07-10 18:46 UTC, happyhye commented on src/pages/product-cart/index.html
> +                </summary>
`<summary>` 태그 안에는 블록 레벨 요소인 `<div>`를 허용하지 않는다고 합니다.
관련 내용 디스코드에 첨부하겠습니다!

2024-07-11 00:41 UTC, devHyeon99 commented on src/pages/product-cart/index.html
> +          <h3 class="sr-only">장바구니 목록</h3>
확인 했습니다!

2024-07-11 00:42 UTC, devHyeon99 commented on src/pages/product-cart/index.html
> +            <li class="cart-category" role="listitem" aria-posinset="1" aria-setsize="3">
확인 하였습니다!

2024-07-11 00:49 UTC, devHyeon99 commented on src/pages/product-cart/index.html
> +              전체선택<span aria-label="선택된 항목 수">(3/3)</span>
<span role="status" aria-live="polite" aria-label="선택된 항목 수">(3/3)</span>

위와 같이 변경 하였습니다.

2024-07-11 01:08 UTC, devHyeon99 commented on src/pages/product-cart/index.html
> +                </summary>
div 대신 span 태그 활용 하였습니다.

2024-07-11 01:18 UTC, happyhye approved these changes
검토 완료!👏👏👏

2024-07-11 01:19 UTC, merged